### ISSUE TITLE
`Termux` 下无法使用 `install.sh` 安装 `PhoenixBuilder`

### ISSUE THREAD

**Issue by Happy2018new** [LNSSPsd/PhoenixBuilder#284]
对于成功执行了下述命令的 `Termux` ，尝试使用 `install.sh` 时会产生以下的报错。
```shell
$ apt update
$ apt upgrade
```
***
![image](https://github.com/LNSSPsd/PhoenixBuilder/assets/109064184/3fed669a-6201-40f0-9d68-0fd7cb53e6ed)

**Comment by Happy2018new** [comment]
```
Sierra[忙，勿扰] 23:41
哦找到了

因为安装脚本用到了which

Happy2018new 23:42
那为什么之前没事

（？

Sierra[忙，勿扰] 23:42
Happy2018new：那为什么之前没事

      
    
@Happy2018new 因为自带 执行完upgrade之后莫名其妙用不了了

就得再手动装一次

[表情344]
```

**Comment by Torrekie** [comment]
Can you confirm if `command -v apt` is available?

**Comment by Happy2018new** [comment]
> Can you confirm if `command -v apt` is available?

它是可用的。

**Comment by CMA2401PT** [comment]
termux的包管理感觉还是不太靠谱，或许应该在termux上放弃使用包管理

**Comment by Torrekie** [comment]
> termux的包管理感觉还是不太靠谱，或许应该在termux上放弃使用包管理

As Termux is different with normal Android / Linux environment, manage dependencies with package managers is essential. Vendor of Termux is doing much more platform-specific patching and maintaining than upstream, same logic with distros like Debian and Homebrew. De facto most common platforms has been developed with very well performed bug tracking systems so that we can completely believe the stability of softwares/dependencies that maintained by them.

**Comment by Happy2018new** [comment]
在缺失 `which` 的情况下依旧无法使用脚本。

**Comment by Happy2018new** [comment]
![Cache_-251c403bc54d984c](https://github.com/LNSSPsd/PhoenixBuilder/assets/109064184/62756a8e-2d23-46ad-a297-f7bed0c3b8c8)

**Comment by Happy2018new** [comment]
![Screenshot_20230716_001713](https://github.com/LNSSPsd/PhoenixBuilder/assets/109064184/890f580d-4d34-4641-b600-e6eaba5d3b20)

**Comment by Torrekie** [comment]
This is going to be fixed when I got time

**Comment by CMA2401PT** [comment]
或许我们还是应该在termux上放弃使用包管理，当然，之前我们讨论过这个话题，但是等等，先听我说完：

这个问题和包管理的重要性并没有什么关系，也和大家是否努力维护和其质量无关

这个问题纯属来自安卓约定俗成的使用习惯和包管理存的矛盾

经过一些研究，我有很大的把握可以解释之前遇到的那种情况：为什么那么多人termux的包管理损坏了？

就像linux那样，尽管从文件系统和包管理都具有一定的恢复能力，但是包管理仍是一个精密的系统。就像我们知道的那样，在其操作进行一半——特别是写入配置或数据库/更新自己的数据时——打断它，则很容易使之陷入可修复/不可修复的损坏中
自然，有经验的linux使用者很容易避免这种情况出现，比如等待操作完成/报错，使用正确的组合键向包管理发送停止信号而不是把电源线直接拔掉
但是，安卓的操作逻辑不是这样，当用户遇到问题（或者没有遇到问题，只是卡住或者在进行某些耗时的操作时）习惯性的会直接上划关闭 termux——这和直接拔掉电源线无异——并导致包管理以一定概率陷入故障状态。而期待这些用户自行修复包管理错误似乎是不合理的。

因此，我建议完全不依赖包管理完成这个操作，或者至少给一个fallback

**Comment by Torrekie** [comment]
`LOCAL=1` was already a fallback method instead of using APT/dpkg

**Comment by Torrekie** [comment]
Users should always use package managers when there was one exists in the *nix world, no matter how Android users thinks the usage of Termux. Complying users' stupidity is completely nonsense.

No way for us to provide a *convenient* way to install a copy of FastBuilder CLI when they are not familiar with package managers, yes of course we provided an alternative way to install the binary without calling APT on Termux which is setting `LOCAL=1` environment variable, this has been explicitly mentioned when users encountered problems.

The only way to solve this problem is to release a FastBuilder GUI with such 'Android Logic', since we don't have a proper GUI solution currently, this issue will be closed.

**Comment by Happy2018new** [comment]
Rectify: Bugs related to this issue has been fixed in 910663acdc40888fb30478d1008be05d87a4fed8

**Comment by CMA2401PT** [comment]
现在，这个问题又在macos上出现了…找不到which，这似乎是因为没有执行过 xcode-select --install 导致的，但是我并没有全新的苹果电脑可以验证这一点

**Comment by Happy2018new** [comment]
不过一切在 `Termux` 工作正常，即便我尝试使用 `pkg uninstall which` 也依然可以正常使用 `install.sh`

**Comment by CMA2401PT** [comment]
大概是我没说清楚？我说的是macos，没有执行过 xcode-select --install 的macos，不是termux

**Comment by Happy2018new** [comment]
> 大概是我没说清楚？我说的是macos，没有执行过 xcode-select --install 的macos，不是termux

这不是你的问题，我只是想强调一下 `Termux` 应该没有这个问题了（

**Comment by CMA2401PT** [comment]
如果我没跑题的话，我的核心观点并不是指这个脚本没有正确工作，而是指出termux包管理容易出错的原因，并建议不要依赖termux的包管理或者当依赖包管理的安装出错时自动fallback到不依赖的实现，大概

**Comment by Happy2018new** [comment]
哈哈，这无所谓，因为托莱奇已经回答你了，但这个议题跟”是否移除包管理“这件事没有太大的关联，所以我把 `Not Planned` 改为了 `Closed` 。
不过现在看起来指望移除包管理已经是不可能的事了（

**Comment by Happy2018new** [comment]
但你不是说 `macos` 也出现了类似的问题吗，或许应该 `Reopen` ？

**Comment by CMA2401PT** [comment]
> 但你不是说 `macos` 也出现了类似的问题吗，或许应该 `Reopen` ？

也许，但是我并不打算也没有环境修这个，所以就不open了

**Comment by Torrekie** [comment]
`which` on macOS is a part of [shell_cmds](https://github.com/apple-oss-distributions/shell_cmds) which is already a shipped command, no business with Xcode CLT, as it not linked with libxcselect.

```
TorrekiedeMBP:proj torrekie$ otool -L /usr/bin/which 
/usr/bin/which (architecture x86_64):
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
/usr/bin/which (architecture arm64e):
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
```
