### ISSUE TITLE
关于等级限制

### ISSUE THREAD

**Issue by maoqijie** [LNSSPsd/PhoenixBuilder#352]
服主号被防沉迷的情况下，使用fb将会变得非常困难。所以能否在机器人进入租赁服的过程中，提供一个输入IP进入服务器的选项（可以使用国际版api验证IP是否与卡槽中的服务器号对于对应），以此来方便服主的使用

**Comment by Happy2018new** [comment]
I think this feature is not very necessary.
Why not create a new robot account to instead the older one?

**Comment by Happy2018new** [comment]
I guess you maybe not very know how the robot work.
To ensure legitimacy, Netease request each user use legal way to get `server_code, transfer_data, MCPCheckNum, etc`.
So, we **can't** bypass the system, because use other ways can only get `server_code`, **but not** `transfer_data` and `MCPChecknum`.
